// ============================================================
// lib/gov-sources/registry.js
//
// Single declarative catalog of every government API / data feed
// the MMT codebase integrates against, plus the priority sources
// we WANT to integrate next. Consumed by:
//
//   - scripts/gov-check.js  (local CLI: `npm run gov:check`)
//   - netlify/functions/gov-source-check.js  (in-prod health probe)
//   - docs/government-api-integration-audit.md  (human-readable
//       counterpart; keep in sync)
//
// Source status semantics:
//   "configured"          — env vars present (where needed) AND a
//                           backend fetcher exists in the repo.
//                           A check WILL probe the public endpoint
//                           with a 1-byte / HEAD-equivalent request.
//   "missing_credentials" — fetcher exists but the env var(s) it
//                           needs are unset in the runtime env.
//   "endpoint_unavailable"— documented endpoint did not return 2xx
//                           on a recent probe; treat as not usable
//                           until upstream confirms.
//   "not_implemented"     — no backend fetcher in the repo yet.
//
// Anti-fabrication contract: registry entries reflect what's
// actually in `netlify/functions/lib/*.js`. If a fetcher is removed,
// drop the entry; don't leave a stale `configured` claim.
// ============================================================

const SOURCES = [
  // ============================================================
  // TIER 1 — Core acquisition + policy intelligence
  // ============================================================
  {
    id: "sam_opportunities",
    tier: 1,
    label: "SAM.gov Opportunities",
    domain: "acquisition",
    base_url: "https://api.sam.gov/prod/opportunities/v2/search",
    auth_env: ["SAM_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/federal-data-apis.js",
    function_export: "searchSAMOpportunities",
    docs_url: "https://open.gsa.gov/api/get-opportunities-public-api/",
    rotation_days: 90,
    probe: { path: "?limit=1&postedFrom=01/01/2026&postedTo=01/02/2026", required_keys: ["SAM_GOV_API_KEY"] },
  },
  {
    id: "sam_entities",
    tier: 1,
    label: "SAM.gov Entity Management",
    domain: "acquisition",
    base_url: "https://api.sam.gov/entity-information/v4/entities",
    auth_env: ["SAM_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/federal-data-apis.js",
    function_export: "searchSAMEntities",
    docs_url: "https://open.gsa.gov/api/entity-api/",
    rotation_days: 90,
    probe: { required_keys: ["SAM_GOV_API_KEY"] },
  },
  {
    id: "sam_psc",
    tier: 1,
    label: "SAM.gov Product Service Code (PSC) Public API",
    domain: "acquisition",
    base_url: "https://api.sam.gov/prod/locationservices/v1/api/publicpsclookup",
    auth_env: ["SAM_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "lib/gov-sources/fetchers/sam-psc.js",
    function_export: "lookupPSC",
    docs_url: "https://open.gsa.gov/api/PSC-Public-API/",
    rotation_days: 90,
    probe: { required_keys: ["SAM_GOV_API_KEY"] },
  },
  {
    id: "sam_contract_awards",
    tier: 1,
    label: "SAM.gov Contract Awards (system account)",
    domain: "acquisition",
    base_url: "https://api.sam.gov/prod/contractData/v3/api/awards",
    auth_env: ["SAM_SYSTEM_ACCOUNT_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/sam-contract-awards.js",
    function_export: null,
    docs_url: null,
    notes: "Per CLAUDE.md sprint 2026-05-07, SAM.gov Contract Data API was decommissioned 2026-02-24; FPDS legacy SOAP is also retired. USASpending v2 is the canonical replacement for award lookup.",
  },
  {
    id: "sam_wage_determinations",
    tier: 1,
    label: "SAM.gov Wage Determinations",
    domain: "acquisition",
    base_url: "https://api.sam.gov/prod/wageDeterminationOnline/v1",
    auth_env: ["SAM_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/sam-wage-determinations.js",
    function_export: null,
  },
  {
    id: "sam_assistance",
    tier: 1,
    label: "SAM.gov Assistance Listings (CFDA)",
    domain: "grants",
    base_url: "https://api.sam.gov/prod/fal/v1/programs",
    auth_env: ["SAM_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/sam-assistance.js",
    function_export: null,
  },
  {
    id: "usaspending",
    tier: 1,
    label: "USAspending awards / spending / agencies",
    domain: "acquisition",
    base_url: "https://api.usaspending.gov/api/v2",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/federal-data-apis.js",
    function_export: "searchUSASpending",
    docs_url: "https://api.usaspending.gov/",
    probe: { path: "/references/toptier_agencies/", required_keys: [] },
  },
  {
    id: "federal_register",
    tier: 1,
    label: "Federal Register documents",
    domain: "policy",
    base_url: "https://www.federalregister.gov/api/v1",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/federal-data-apis.js",
    function_export: "searchFederalRegister",
    docs_url: "https://www.federalregister.gov/developers/documentation/api/v1",
    probe: { path: "/documents.json?per_page=1", required_keys: [] },
  },
  {
    id: "regulations_gov",
    tier: 1,
    label: "Regulations.gov dockets + comments",
    domain: "policy",
    base_url: "https://api.regulations.gov/v4",
    auth_env: ["REGULATIONS_GOV_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/regulations-gov.js",
    function_export: "searchDockets",
    docs_url: "https://open.gsa.gov/api/regulationsgov/",
    notes: "Falls back to DEMO_KEY (tightly rate-limited) if env var unset.",
    probe: { path: "/dockets?page[size]=1", required_keys: [] },
  },
  {
    id: "ecfr",
    tier: 1,
    label: "Electronic CFR (eCFR) search + section fetch",
    domain: "policy",
    base_url: "https://www.ecfr.gov/api",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/ecfr-api.js",
    function_export: "searchECFR",
    docs_url: "https://www.ecfr.gov/developers/documentation/api/v1",
    probe: { path: "/search/v1/results?query=FAR&per_page=1", required_keys: [] },
  },
  {
    id: "govinfo",
    tier: 1,
    label: "GovInfo (Congress reports, CFR packages, bills, hearings)",
    domain: "policy",
    base_url: "https://api.govinfo.gov",
    auth_env: ["CONGRESS_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/govinfo-api.js",
    function_export: null,
    docs_url: "https://www.govinfo.gov/developers",
    notes: "Same API key as Congress.gov.",
    probe: { required_keys: ["CONGRESS_API_KEY"] },
  },
  {
    id: "congress",
    tier: 1,
    label: "Congress.gov bills / members / committees",
    domain: "policy",
    base_url: "https://api.congress.gov/v3",
    auth_env: ["CONGRESS_API_KEY"],
    auth_pattern: "query:api_key",
    function_lib: "netlify/functions/lib/congress-api.js",
    function_export: null,
  },
  {
    id: "gao_reports",
    tier: 1,
    label: "GAO Reports (search + RSS surrogate)",
    domain: "oversight",
    base_url: "https://www.gao.gov/reports-testimonies",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/federal-data-apis.js",
    function_export: "searchGAOReports",
    notes: "No official public GAO API; library uses search surrogate.",
  },
  {
    id: "gsa_calc",
    tier: 1,
    label: "GSA CALC+ labor-rate ceilings",
    domain: "pricing",
    base_url: "https://calc.gsa.gov/api/2",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/calc-rates.js",
    function_export: "searchCALC",
    docs_url: "https://open.gsa.gov/api/dx-calc-api/",
    probe: { path: "/contracts/?q=program%20manager&page_size=1", required_keys: [] },
  },
  {
    id: "cisa_kev",
    tier: 1,
    label: "CISA Known Exploited Vulnerabilities (KEV)",
    domain: "cyber",
    base_url: "https://www.cisa.gov/sites/default/files/feeds",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "lib/gov-sources/fetchers/cisa-kev.js",
    function_export: "fetchKev",
    docs_url: "https://github.com/cisagov/kev-data",
    probe: { path: "/known_exploited_vulnerabilities.json", required_keys: [] },
  },
  {
    id: "nvd_cve",
    tier: 1,
    label: "NIST National Vulnerability Database (NVD) CVEs",
    domain: "cyber",
    base_url: "https://services.nvd.nist.gov/rest/json/cves/2.0",
    auth_env: ["NVD_API_KEY"],
    auth_pattern: "header:apiKey (optional)",
    function_lib: "lib/gov-sources/fetchers/nvd.js",
    function_export: "searchCves",
    docs_url: "https://nvd.nist.gov/developers",
    notes: "Key optional; raises rate limits.",
    probe: { path: "?resultsPerPage=1", required_keys: [] },
  },
  {
    id: "acquisition_gateway",
    tier: 1,
    label: "GSA Acquisition Gateway Listings API",
    domain: "acquisition",
    base_url: "https://api.gsa.gov/acquisitiongateway/api/v4.0",
    auth_env: ["GSA_API_KEY"],
    auth_pattern: "header:x-api-key",
    function_lib: "lib/gov-sources/fetchers/acquisition-gateway.js",
    function_export: "probeEndpoint",
    docs_url: "https://open.gsa.gov/api/ag-api/",
    notes: "GSA Open page contradicts itself (says no APIs AND describes v4.0). DEMO_KEY documents endpoint returned 404 in prior testing. Probe-only until GSA confirms.",
    expected_status: "endpoint_unavailable",
    probe: { required_keys: ["GSA_API_KEY"] },
  },
  {
    id: "fco",
    tier: 1,
    label: "Federal Procurement Forecasting (FCO)",
    domain: "acquisition",
    base_url: "https://ag-dashboard.acquisitiongateway.gov",
    auth_env: [],
    auth_pattern: "unknown",
    function_lib: null,
    function_export: null,
    docs_url: "https://www.gsa.gov/small-business/find-opportunities",
    notes: "OFPP 2025 memo describes API integration for agency UPLOAD, not necessarily public READ. No public-read endpoint confirmed.",
    expected_status: "not_implemented",
  },

  // ============================================================
  // TIER 2 — Health, grants, innovation, market signal
  // ============================================================
  {
    id: "grants_gov",
    tier: 2,
    label: "Grants.gov opportunity search",
    domain: "grants",
    base_url: "https://www.grants.gov/grantsws/rest",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/grants-api.js",
    function_export: null,
  },
  {
    id: "simpler_grants",
    tier: 2,
    label: "Simpler.Grants.gov API",
    domain: "grants",
    base_url: "https://api.simpler.grants.gov",
    auth_env: ["SIMPLER_GRANTS_API_KEY"],
    auth_pattern: "header:X-Auth",
    function_lib: null,
    function_export: null,
    docs_url: "https://simpler.grants.gov/developers",
    expected_status: "not_implemented",
  },
  {
    id: "nih_reporter",
    tier: 2,
    label: "NIH RePORTER (grants, projects, publications)",
    domain: "health-rd",
    base_url: "https://api.reporter.nih.gov/v2",
    auth_env: [],
    auth_pattern: "none",
    function_lib: null,
    function_export: null,
    docs_url: "https://api.reporter.nih.gov/",
    expected_status: "not_implemented",
  },
  {
    id: "sbir_awards",
    tier: 2,
    label: "SBIR/STTR awards + solicitations + companies",
    domain: "small-business",
    base_url: "https://www.sbir.gov/api",
    auth_env: [],
    auth_pattern: "none",
    function_lib: null,
    function_export: null,
    docs_url: "https://www.sbir.gov/api",
    expected_status: "not_implemented",
  },
  {
    id: "cms_provider_data",
    tier: 2,
    label: "CMS Provider Data",
    domain: "health-policy",
    base_url: "https://data.cms.gov/provider-data",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/cms-provider-data.js",
    function_export: null,
  },
  {
    id: "onc_chpl",
    tier: 2,
    label: "ONC Certified Health IT Product List (CHPL)",
    domain: "health-policy",
    base_url: "https://chpl.healthit.gov/rest",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/onc-chpl-api.js",
    function_export: null,
  },
  {
    id: "onc_healthit",
    tier: 2,
    label: "ONC HealthIT data",
    domain: "health-policy",
    base_url: "https://www.healthit.gov",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/onc-healthit-api.js",
    function_export: null,
  },
  {
    id: "clinicaltrials",
    tier: 2,
    label: "ClinicalTrials.gov v2",
    domain: "health-rd",
    base_url: "https://clinicaltrials.gov/api/v2",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/clinicaltrials-api.js",
    function_export: null,
  },
  {
    id: "pubmed",
    tier: 2,
    label: "PubMed (NCBI E-utilities)",
    domain: "health-rd",
    base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/pubmed-api.js",
    function_export: null,
  },
  {
    id: "bls",
    tier: 2,
    label: "Bureau of Labor Statistics",
    domain: "economic",
    base_url: "https://api.bls.gov/publicAPI/v2",
    auth_env: [],
    auth_pattern: "header:BLS-Key (optional)",
    function_lib: "netlify/functions/lib/bls-api.js",
    function_export: null,
  },
  {
    id: "usajobs",
    tier: 2,
    label: "USAJOBS listings",
    domain: "labor",
    base_url: "https://data.usajobs.gov/api",
    auth_env: ["USAJOBS_API_KEY", "USAJOBS_USER_EMAIL"],
    auth_pattern: "header:Authorization-Key + User-Agent",
    function_lib: "netlify/functions/lib/usajobs-api.js",
    function_export: null,
  },
  {
    id: "sec_edgar",
    tier: 2,
    label: "SEC EDGAR (10-K, 10-Q, 8-K filings)",
    domain: "market",
    base_url: "https://data.sec.gov",
    auth_env: [],
    auth_pattern: "User-Agent required",
    function_lib: "netlify/functions/lib/sec-edgar-api.js",
    function_export: null,
  },
  {
    id: "it_dashboard",
    tier: 2,
    label: "Federal IT Dashboard",
    domain: "acquisition",
    base_url: "https://itdashboard.gov",
    auth_env: [],
    auth_pattern: "none",
    function_lib: "netlify/functions/lib/it-dashboard-api.js",
    function_export: null,
  },

  // ============================================================
  // TIER 3 — Manual / scrape-only / unconfirmed
  // ============================================================
  {
    id: "va_oig",
    tier: 3,
    label: "VA OIG Reports",
    domain: "oversight",
    base_url: "https://www.vaoig.gov/reports/all",
    auth_env: [],
    auth_pattern: "none (no public API confirmed)",
    function_lib: null,
    function_export: null,
    expected_status: "not_implemented",
    notes: "Monitor via RSS/scrape only if upstream terms allow.",
  },
  {
    id: "oversight_gov",
    tier: 3,
    label: "Oversight.gov (cross-IG audits)",
    domain: "oversight",
    base_url: "https://www.oversight.gov",
    auth_env: [],
    auth_pattern: "none (no public API confirmed)",
    function_lib: null,
    function_export: null,
    expected_status: "not_implemented",
  },
  {
    id: "acquisition_gov_forecasts",
    tier: 3,
    label: "Acquisition.gov agency procurement forecasts",
    domain: "acquisition",
    base_url: "https://www.acquisition.gov/procurement-forecasts",
    auth_env: [],
    auth_pattern: "none (no public API confirmed)",
    function_lib: null,
    function_export: null,
    expected_status: "not_implemented",
    notes: "Structured-page monitor target. No API.",
  },
];

function getSource(id) {
  return SOURCES.find((s) => s.id === id) || null;
}

function listSources({ tier } = {}) {
  if (tier == null) return SOURCES.slice();
  return SOURCES.filter((s) => s.tier === tier);
}

module.exports = { SOURCES, getSource, listSources };
