/**
 * contract-facts.js — Verified ground truth for federal health IT contracts.
 *
 * Source of truth for known contract data, stale pattern detection,
 * and vehicle status. Values sourced from contracts.json (Sprint 1).
 *
 * @module contract-facts
 */

const KNOWN_FACTS = {
  "mhs-genesis-electronic-health-record": {
    name: "MHS GENESIS (Electronic Health Record)",
    agency: "Defense Health Agency (DHA)",
    vendor: "Leidos / Oracle Health (Cerner)",
    value: "~$5.5B (expanded 2018) + $1.4B sole-source extension through 2028",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://www.health.mil/Military-Health-Topics/Technology/MHS-GENESIS", "https://www.meritalk.com/articles/dod-planning-1-4b-ehr-contract-extension-with-leidos/"],
  },
  "community-care-network-ccn-next-gen": {
    name: "Community Care Network (CCN) Next Gen",
    agency: "Department of Veterans Affairs",
    vendor: "TBD — solicitation active, proposals due April 3, 2026",
    value: "Est. $65B+ (multi-region IDIQ)",
    status: "upcoming",
    naics: "524292",
    lastVerified: "2026-03-17",
    sources: ["https://sam.gov/opp/7b2734002e4048bfa2ac4cc5b0479930/view"],
  },
  "t4ng-t4ng2-va-it-services": {
    name: "T4NG / T4NG2 (VA IT Services)",
    agency: "Department of Veterans Affairs",
    vendor: "Multiple award (T4NG2 awardees)",
    value: "$60.7B ceiling (T4NG2)",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://sam.gov"],
  },
  "federal-electronic-health-record-modernization-fehrm": {
    name: "Federal Electronic Health Record Modernization (FEHRM)",
    agency: "DoD / VA Joint Program",
    vendor: "Oracle Health (Cerner)",
    value: "$37B–$50B lifecycle estimate (combined DoD/VA)",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://www.fehrm.gov"],
  },
  "va-ehr-modernization-ehrm": {
    name: "VA EHR Modernization (EHRM)",
    agency: "Department of Veterans Affairs",
    vendor: "Oracle Health (Cerner)",
    value: "~$37B lifecycle estimate",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://digital.va.gov/ehr-modernization/ehr-deployment-schedule/"],
  },
  "tricare-managed-care-support-t-5-mcs": {
    name: "TRICARE Managed Care Support — T-5 (MCS)",
    agency: "Defense Health Agency (DHA)",
    vendor: "Humana Military (East), TriWest Healthcare Alliance (West)",
    value: "Humana East $7.34B (CY2026 option), Evernorth $719.4M (pharmacy CY2026)",
    status: "active",
    naics: "524292",
    lastVerified: "2026-03-17",
    sources: ["https://newsroom.tricare.mil/News/TRICARE-News/Article/3776346/"],
  },
  "enterprise-intelligence-data-solutions-eids": {
    name: "Enterprise Intelligence & Data Solutions (EIDS)",
    agency: "Defense Health Agency (DHA)",
    vendor: "SpinSys-Diné (PMO COOP), Koniag IT Systems ($94.4M AWS cloud, 8(a) sole-source)",
    value: "$650M ceiling",
    status: "active",
    naics: "541611",
    lastVerified: "2026-03-17",
    sources: ["https://orangeslices.ai/koniag-subsidiary-scores-94m-dha-eids-pmo-aws-idiq/"],
  },
  "defense-health-agency-telehealth-programs": {
    name: "Defense Health Agency Telehealth Programs",
    agency: "Defense Health Agency (DHA)",
    vendor: "Amwell + Leidos (Digital First, $180M task order)",
    value: "$180M (primary)",
    status: "active",
    naics: "621999",
    lastVerified: "2026-03-17",
    sources: ["https://business.amwell.com/about-us/news/press-releases/2023/u.s.-defense-health-agency-selects-amwell-and-leidos"],
  },
  "va-health-connect-iht-20": {
    name: "VA Health Connect / IHT 2.0",
    agency: "Department of Veterans Affairs",
    vendor: "Tribility, Titan-Auxo, Rios Partners, Reefpoint Group, Prometheus Federal Services, Blue Water Thinking, Arrow ARC, Agile4Vets",
    value: "$14B / 10-year (IHT 2.0 IDIQ)",
    status: "active",
    naics: "621999",
    lastVerified: "2026-03-17",
    sources: ["https://orangeslices.ai/va-vha-releases-draft-rfp-for-14b-iht-2-0-idiq/"],
  },
  "military-health-system-enterprise-imaging": {
    name: "Military Health System Enterprise Imaging",
    agency: "Defense Health Agency (DHA)",
    vendor: "Multiple vendors",
    value: "Various",
    status: "active",
    naics: "334510",
    lastVerified: "2026-03-17",
    sources: ["https://govtribe.com/opportunity/federal-contract-opportunity/noi-to-sole-source-to-imaging-service-solutions"],
  },
  "ihs-health-it-modernization-rpms-replacement": {
    name: "IHS Health IT Modernization (RPMS Replacement)",
    agency: "Indian Health Service (IHS)",
    vendor: "General Dynamics IT (GDIT)",
    value: "$2.5B IDIQ",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://www.gdit.com/perspectives/latest/gdit-awarded-health-it-modernization-contract/"],
  },
  "tpharm5-tricare-pharmacy": {
    name: "TPharm5 (TRICARE Pharmacy)",
    agency: "Defense Health Agency (DHA)",
    vendor: "Express Scripts / Evernorth",
    value: "$4.28B",
    status: "active",
    naics: "524292",
    lastVerified: "2026-03-17",
    sources: ["https://sam.gov/opp/d0560f19a2734ac59e21d379b0cd1941/view"],
  },
  "cdm-defend-health-data-cybersecurity": {
    name: "CDM DEFEND (Health Data Cybersecurity)",
    agency: "CISA/DHS",
    vendor: "Booz Allen Hamilton",
    value: "$1.2B ceiling",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://orangeslices.ai/booz-allen-awarded-421m-cdm-defend-contract/"],
  },
  "dha-enterprise-generative-ai": {
    name: "DHA Enterprise Generative AI",
    agency: "Defense Health Agency (DHA)",
    vendor: "Ask Sage, Inc.",
    value: "Undisclosed (IL5)",
    status: "active",
    naics: "541512",
    lastVerified: "2026-03-17",
    sources: ["https://orangeslices.ai/ask-sage-dha-enterprise-generative-ai/"],
  },
  "tefca-rce-health-information-exchange": {
    name: "TEFCA / RCE (Health Information Exchange)",
    agency: "HHS ONC/ASTP",
    vendor: "The Sequoia Project",
    value: "$12.8M (with extensions to $21.8M)",
    status: "active",
    naics: "541611",
    lastVerified: "2026-03-17",
    sources: ["https://orangeslices.ai/contract-award-21-8m-hhs-tefca-rce/"],
  },
  "cms-rural-health-transformation": {
    name: "CMS Rural Health Transformation",
    agency: "Centers for Medicare & Medicaid Services (CMS)",
    vendor: "Multiple (50-state awards)",
    value: "$50B (2026-2030)",
    status: "active",
    naics: "541611",
    lastVerified: "2026-03-17",
    sources: ["https://www.cms.gov/newsroom/press-releases/cms-announces-50-billion-awards-strengthen-rural-health-all-50-states"],
  },
};

const CANCELLED_VEHICLES = ["CIO-SP4"];

const ACTIVE_VEHICLES = ["OASIS+", "CIO-SP3", "Alliant 3", "T4NG2", "OMNIBUS IV", "SBIR/STTR"];

const STALE_PATTERNS = [
  { pattern: /T-5 BPA/i, correction: "T4NG / T4NG2" },
  { pattern: /Health Net Federal/i, correction: "TriWest Healthcare Alliance" },
  { pattern: /\$4\.3B.*initial/i, correction: "~$5.5B + $1.4B extension" },
  { pattern: /\$16B.*combined/i, correction: "$37B-$50B lifecycle" },
  { pattern: /paused at some/i, correction: "Resuming April 2026" },
  { pattern: /CIO-SP4(?!.*cancel)/i, correction: "CIO-SP4 cancelled Feb 2026" },
];

module.exports = { KNOWN_FACTS, CANCELLED_VEHICLES, ACTIVE_VEHICLES, STALE_PATTERNS };
