-- Run in Supabase Dashboard → SQL Editor
-- service_role key (Netlify functions) bypasses RLS automatically

ALTER TABLE IF EXISTS mp_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_scoring_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS marketpulse_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_feature_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS marketpulse_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_processed_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ops_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bounce_suppression ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mp_subscriptions ENABLE ROW LEVEL SECURITY;
